### ISSUE TITLE
TVOC available

### ISSUE THREAD

**Issue by marcmagus** [handro123/AirGradient-DIY-Pro-ESPHome#1]
AirGradient is now selling TVOC kits as expected. The one you can buy directly from them along with a Pro kit is an SGP41 TVOC/NOx sensor.

I seem to be having success with the following snippet:

```
  - platform: sgp4x
  # https://esphome.io/components/sensor/sgp4x.html
    voc:
      name: "TVOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox
    compensation:
      humidity_source: humidity
      temperature_source: temp
    update_interval: 60s
```

Thanks for sharing your code, it was a great starting place for getting my own up and running.
